exp_name: exp_2
algo: vpg
env: LunarLanderContinuous-v2
lr: 1e-2
hidden_sizes: [32]
n_epochs: 1000
batch_size: 5000
render: False
device: cuda:0
trained_model_path: ./algorithms/vpg/my_vpg_cont.pth
test: False
